version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
      - gradlew bootJar
artifacts:
  files:
    - build/libs/java-demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes